name: Testes de API-CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: http://localhost:3000

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.8'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Start ServeRest (local)
        run: npx serverest@latest > serverest.log 2>&1 &

      - name: Aguardar API ficar disponível
        run: npx wait-on http://localhost:3000/usuarios

      - name: Test e Report
        run: npm test

      - name: Upload Reports (mochawesome)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report/
